ALTER TABLE sgigjreldocumento ADD DESPACHO_INTERROMPIDO_ID varchar(100) NULL;
ALTER TABLE sgigjreldocumento CHANGE DESPACHO_INTERROMPIDO_ID DESPACHO_INTERROMPIDO_ID varchar(100) NULL AFTER NOTIFICACAO_PROCESSO_ID;

ALTER TABLE glbuser MODIFY COLUMN FLAG_NOTIFICACAO varchar(1) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL;
